### ISSUE TITLE
IND_INJERROR_LOADDLL on Windows 10 Version 2004

### ISSUE THREAD

**Issue by AChenny** [m417z/7-Taskbar-Numberer#1]
Getting a error "IND_INJERROR_LOADDLL" when starting up taskbar numberer on Windows 10 Version 2004 OS Build 19041.264. GUI will load but the taskbar numbers will not show up.

**Comment by m417z** [comment]
Should be fixed in version 9.9.

**Comment by M-Momtaz** [comment]
> Should be fixed in version 9.9.

Still exist, Is version 9.9 released ?

**Comment by m417z** [comment]
Yes, it was released when I posted the comment. I believe that's a new incompatibility, caused by update KB4568831 of Windows 10 version 2004. I didn't look at it yet, but I know that this update broke 7+ Taskbar Tweaker.

**Comment by AChenny** [comment]
I believe the last update KB4566782 in Windows 10 2004 also broke Taskbar Numberer 7+

**Comment by m417z** [comment]
Please try the newly released version 10.2.

**Comment by M-Momtaz** [comment]
> Please try the newly released version 10.2.

It working properly, Thanks @m417z
