### ISSUE TITLE
rammichael.com down, upload releases on GitHub?

### ISSUE THREAD

**Issue by Otiel** [m417z/7-Taskbar-Numberer#2]
https://rammichael.com is down currently. I wanted to retrieve the latest version of 7+ Taskbar Numberer.

Do you mind uploading the binaries on GitHub releases as an addition to your website for such circonstances?

**Comment by m417z** [comment]
The website is back up. It happens sometimes that it's down, but it's not too often, and I'd rather not maintain two locations of the binaries, sorry.

**Comment by Otiel** [comment]
I understand, thanks for the reply!
