### ISSUE TITLE
-hidewnd doesn't seem to work

### ISSUE THREAD

**Issue by DeadstarIII** [m417z/7-Taskbar-Numberer#3]
Hey dear dev,
I tried using -hidewind after the target with -v2
it failed to work, it keeps opening the dialog whenever I run it.

**Comment by m417z** [comment]
Hi,
The command line switch is `-hidewnd`, not `-hidewind`.
https://github.com/m417z/7-Taskbar-Numberer/blob/41250bad01ccd42da6b405604805a4133a6b2a5f/exe/exe.c#L190
